Algoritmo "soma"

Var


   X, Y, SOMA : InteirO

Inicio


      Escreva("Digite o valor de X: ")
      Leia(X)
      
      Escreva("Digite o valor de Y: ")
      Leia(Y)
      
      SOMA := X + Y;
      
      EscrevaL("SOMA = ", SOMA)
      
      Escreva("Digite o valor de X: ")
      Leia(X)

      Escreva("Digite o valor de Y: ")
      Leia(Y)

      SOMA := X + Y;

      Escreva("SOMA = ", SOMA)


Fimalgoritmo