Algoritmo "tabuada"
// Disciplina  : Algoritmos e Lógica de Programação
// Aluno       : Fábio Pina
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Data atual  : 29/9/2021
Var

   N, i, produto : InteirO

Inicio


      Escreva("Digite o número da tabuada: ")
      Leia(N)
      
      Para i de 1 AtE 10 Faca
      
           produto <- N * i
           
           EscrevaL(N, " x ", i, " = ", produto)
      
      FimPara

Fimalgoritmo