Algoritmo "teste-saida"
// Disciplina: Algoritmos e Lógica Programação
// Aluno : Fábio Pina 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Data atual  : 8/9/2021
Var

   a : inteiro
   b : real
   c : caractere
   d : logico
   


Inicio
      a <- 10
      b <- 3.14159
      c <- "Fábio"
      d <- VERDADEIRO
      
      EscrevaL(a)
      EscrevaL(b)
      EscrevaL(c)
      EscrevaL(d)


Fimalgoritmo